"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mockInterviews = exports.mockUsers = exports.mockApplications = void 0;
exports.mockApplications = [
    { company: 'Company 1', date: new Date(), status: 'To Apply' },
    { company: 'Company 2', date: new Date(), status: 'Applied' },
    { company: 'Company 3', date: new Date(), status: 'Interview Scheduled' },
    { company: 'Company 4', date: new Date(), status: 'Interviewing' },
    { company: 'Company 5', date: new Date(), status: 'Offer Received' },
    { company: 'Company 6', date: new Date(), status: 'Offer Rejected' },
    { company: 'Company 7', date: new Date(), status: 'Rejected' },
    { company: 'Company 8', date: new Date(), status: 'To Apply' },
    { company: 'Company 9', date: new Date(), status: 'Applied' },
    { company: 'Company 10', date: new Date(), status: 'Interview Scheduled' },
    { company: 'Company 11', date: new Date(), status: 'Interviewing' },
    { company: 'Company 12', date: new Date(), status: 'Offer Received' },
    { company: 'Company 13', date: new Date(), status: 'Offer Rejected' },
    { company: 'Company 14', date: new Date(), status: 'Rejected' },
    { company: 'Company 15', date: new Date(), status: 'To Apply' },
    { company: 'Company 16', date: new Date(), status: 'Applied' },
    { company: 'Company 17', date: new Date(), status: 'Interview Scheduled' },
    { company: 'Company 18', date: new Date(), status: 'Interviewing' },
    { company: 'Company 19', date: new Date(), status: 'Offer Received' },
    { company: 'Company 20', date: new Date(), status: 'Offer Rejected' },
    { company: 'Company 21', date: new Date(), status: 'To Apply' },
    { company: 'Company 22', date: new Date(), status: 'Applied' },
    { company: 'Company 23', date: new Date(), status: 'Interview Scheduled' },
    { company: 'Company 24', date: new Date(), status: 'Interviewing' },
    { company: 'Company 25', date: new Date(), status: 'Offer Received' },
    { company: 'Company 26', date: new Date(), status: 'Offer Rejected' },
    { company: 'Company 27', date: new Date(), status: 'Rejected' },
    { company: 'Company 28', date: new Date(), status: 'To Apply' },
    { company: 'Company 29', date: new Date(), status: 'Applied' },
    { company: 'Company 30', date: new Date(), status: 'Interview Scheduled' },
    { company: 'Company 31', date: new Date(), status: 'Interviewing' },
    { company: 'Company 32', date: new Date(), status: 'Offer Received' },
    { company: 'Company 33', date: new Date(), status: 'Offer Rejected' },
    { company: 'Company 34', date: new Date(), status: 'Rejected' },
    { company: 'Company 35', date: new Date(), status: 'To Apply' },
    { company: 'Company 36', date: new Date(), status: 'Applied' },
    { company: 'Company 37', date: new Date(), status: 'Interview Scheduled' },
    { company: 'Company 38', date: new Date(), status: 'Interviewing' },
    { company: 'Company 39', date: new Date(), status: 'Offer Received' },
    { company: 'Company 40', date: new Date(), status: 'Offer Rejected' },
];
exports.mockUsers = [
    { username: 'user1', email: 'user1@example.com', password: 'password1' },
    { username: 'user2', email: 'user2@example.com', password: 'password2' },
    { username: 'user3', email: 'user3@example.com', password: 'password3' },
    { username: 'user4', email: 'user4@example.com', password: 'password4' },
    { username: 'user5', email: 'user5@example.com', password: 'password5' },
    { username: 'user6', email: 'user6@example.com', password: 'password6' },
    { username: 'user7', email: 'user7@example.com', password: 'password7' },
    { username: 'user8', email: 'user8@example.com', password: 'password8' },
    { username: 'user9', email: 'user9@example.com', password: 'password9' },
    { username: 'user10', email: 'user10@example.com', password: 'password10' },
    { username: 'user11', email: 'user11@example.com', password: 'password11' },
    { username: 'user12', email: 'user12@example.com', password: 'password12' },
    { username: 'user13', email: 'user13@example.com', password: 'password13' },
    { username: 'user14', email: 'user14@example.com', password: 'password14' },
    { username: 'user15', email: 'user15@example.com', password: 'password15' },
    { username: 'user16', email: 'user16@example.com', password: 'password16' },
    { username: 'user17', email: 'user17@example.com', password: 'password17' },
    { username: 'user18', email: 'user18@example.com', password: 'password18' },
    { username: 'user19', email: 'user19@example.com', password: 'password19' },
    { username: 'user20', email: 'user20@example.com', password: 'password20' },
];
exports.mockInterviews = [
    { time: '10:00 AM', date: new Date(), result: 'Passed' },
    { time: '2:30 PM', date: new Date(), result: 'Failed' },
    { time: '11:45 AM', date: new Date(), result: 'Passed' },
    { time: '3:15 PM', date: new Date(), result: 'Passed' },
    { time: '9:30 AM', date: new Date(), result: 'Failed' },
    { time: '1:00 PM', date: new Date(), result: 'Passed' },
    { time: '10:30 AM', date: new Date(), result: 'Passed' },
    { time: '4:45 PM', date: new Date(), result: 'Failed' },
    { time: '12:15 PM', date: new Date(), result: 'Passed' },
    { time: '2:00 PM', date: new Date(), result: 'Passed' },
    { time: '11:30 AM', date: new Date(), result: 'Failed' },
    { time: '3:45 PM', date: new Date(), result: 'Passed' },
    { time: '9:15 AM', date: new Date(), result: 'Passed' },
    { time: '1:30 PM', date: new Date(), result: 'Failed' },
    { time: '10:45 AM', date: new Date(), result: 'Passed' },
    { time: '2:15 PM', date: new Date(), result: 'Passed' },
    { time: '11:00 AM', date: new Date(), result: 'Failed' },
    { time: '4:30 PM', date: new Date(), result: 'Passed' },
    { time: '12:45 PM', date: new Date(), result: 'Passed' },
    { time: '3:00 PM', date: new Date(), result: 'Failed' },
    { time: '10:00 AM', date: new Date(), result: 'Passed' },
    { time: '2:30 PM', date: new Date(), result: 'Failed' },
    { time: '11:45 AM', date: new Date(), result: 'Passed' },
    { time: '3:15 PM', date: new Date(), result: 'Passed' },
    { time: '9:30 AM', date: new Date(), result: 'Failed' },
    { time: '1:00 PM', date: new Date(), result: 'Passed' },
    { time: '10:30 AM', date: new Date(), result: 'Passed' },
    { time: '4:45 PM', date: new Date(), result: 'Failed' },
    { time: '12:15 PM', date: new Date(), result: 'Passed' },
    { time: '2:00 PM', date: new Date(), result: 'Passed' },
    { time: '11:30 AM', date: new Date(), result: 'Failed' },
    { time: '3:45 PM', date: new Date(), result: 'Passed' },
    { time: '9:15 AM', date: new Date(), result: 'Passed' },
    { time: '1:30 PM', date: new Date(), result: 'Failed' },
    { time: '10:45 AM', date: new Date(), result: 'Passed' },
    { time: '2:15 PM', date: new Date(), result: 'Passed' },
    { time: '11:00 AM', date: new Date(), result: 'Failed' },
    { time: '4:30 PM', date: new Date(), result: 'Passed' },
    { time: '12:45 PM', date: new Date(), result: 'Passed' },
    { time: '3:00 PM', date: new Date(), result: 'Failed' },
    { time: '10:00 AM', date: new Date(), result: 'Passed' },
    { time: '2:30 PM', date: new Date(), result: 'Failed' },
    { time: '11:45 AM', date: new Date(), result: 'Passed' },
    { time: '3:15 PM', date: new Date(), result: 'Passed' },
    { time: '9:30 AM', date: new Date(), result: 'Failed' },
    { time: '1:00 PM', date: new Date(), result: 'Passed' },
    { time: '10:30 AM', date: new Date(), result: 'Passed' },
    { time: '4:45 PM', date: new Date(), result: 'Failed' },
    { time: '12:15 PM', date: new Date(), result: 'Passed' },
    { time: '2:00 PM', date: new Date(), result: 'Passed' },
    { time: '11:30 AM', date: new Date(), result: 'Failed' },
    { time: '3:45 PM', date: new Date(), result: 'Passed' },
    { time: '9:15 AM', date: new Date(), result: 'Passed' },
    { time: '1:30 PM', date: new Date(), result: 'Failed' },
    { time: '10:45 AM', date: new Date(), result: 'Passed' },
    { time: '2:15 PM', date: new Date(), result: 'Passed' },
    { time: '11:00 AM', date: new Date(), result: 'Failed' },
    { time: '4:30 PM', date: new Date(), result: 'Passed' },
    { time: '12:45 PM', date: new Date(), result: 'Passed' },
    { time: '3:00 PM', date: new Date(), result: 'Failed' },
];
