import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { ReduxProvider } from '@/redux/provider';
import Navbar from '@/(components)/(tsx)/Navbar';
import Layout from '@/(components)/(tsx)/Layout';

const inter = Open_Sans({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Application Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        {/* <Layout children = {children} /> */}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
